name       : python-colorlog
version    : 4.0.2
release    : 4
source     :
    - https://files.pythonhosted.org/packages/fc/30/6ba1282b773e9f44d9cfaafa38b6cc180441307c5fe0edd8db13a8903e3f/colorlog-4.0.2.tar.gz : 3cf31b25cbc8f86ec01fef582ef3b840950dea414084ed19ab922c8b493f9b42
license    : MIT
component  : programming.python
summary    : Log formatting with colors
description: |
    colorlog.ColoredFormatter is a formatter for use with Python's logging module that outputs records using terminal colors.
builddeps  :
    - pkgconfig(python3)
setup      : |
    %python3_setup
install    : |
    %python3_install
