name       : python-colorlog
version    : 6.6.0
release    : 9
source     :
    - https://github.com/borntyping/python-colorlog/archive/refs/tags/v6.6.0.tar.gz : d88a6c0ae92b02ea6d3dbe574a969a8d5555ddeccf1776d330d74d352b445230
homepage   : https://github.com/borntyping/python-colorlog
license    : MIT
component  : programming.python
summary    : A colored formatter for the python logging module
description: |
    colorlog.ColoredFormatter is a formatter for use with Python's logging module that outputs records using terminal colors.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
