name       : python-colorlog
version    : 2.10.0
release    : 2
source     :
    - https://github.com/borntyping/python-colorlog/archive/v2.10.0.tar.gz : f1e3ebbb5ea218ba78d398c0e29c530a1f34d7af5436a9151faaf8f01b358d81
license    : MIT
component  : programming.python
summary    : Log formatting with colors
description: |
    colorlog.ColoredFormatter is a formatter for use with Python's logging module that outputs records using terminal colors.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
