name       : python-colorlog
version    : 6.7.0
release    : 10
source     :
    - https://github.com/borntyping/python-colorlog/archive/refs/tags/v6.7.0.tar.gz : 65d945a7b0d126794df261619d5ace291f367af5a12c7afb9d8836a6a50f3be7
homepage   : https://github.com/borntyping/python-colorlog
license    : MIT
component  : programming.python
summary    : A colored formatter for the python logging module
description: |
    colorlog.ColoredFormatter is a formatter for use with Python's logging module that outputs records using terminal colors.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
