name       : python-colorlog
version    : 4.7.2
release    : 6
source     :
    - https://github.com/borntyping/python-colorlog/archive/v4.7.2.tar.gz : 807eaf34dc122f9ca012af045203f10147304452eb93962a43bdd1ce14289f60
homepage   : https://github.com/borntyping/python-colorlog
license    : MIT
component  : programming.python
summary    : A colored formatter for the python logging module
description: |
    colorlog.ColoredFormatter is a formatter for use with Python's logging module that outputs records using terminal colors.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
