name       : python-colorlog
version    : 4.1.0
release    : 5
source     :
    - https://github.com/borntyping/python-colorlog/archive/v4.1.0.tar.gz : 9c431bdd31b5843a8e59d779cf518426cfd91c14f2776680f43bcdf6872d40ab
license    : MIT
component  : programming.python
summary    : A colored formatter for the python logging module
description: |
    colorlog.ColoredFormatter is a formatter for use with Python's logging module that outputs records using terminal colors.
builddeps  :
    - pkgconfig(python3)
setup      : |
    %python3_setup
install    : |
    %python3_install
